version: '3.3'
services:
  frontend:
    image: gerardomares/npolink:frontend
    volumes:
      - ./frontend:/usr/frontend
    ports:
      - "80:3000"
  backend:
    image: gerardomares/npolink:backend
    volumes:
      - ./backend:usr/src/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=npolinkapi.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@npolink-db:5432/npolink_prod
